# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 6 Free Solid:style=Solid:size=13
awesome_brands: &awesome_brands Font Awesome 6 Brands Regular:style=Regular:size=13

std_overline: &std_overline {overline: { size: 1, color: ddddddff}}

# This is THE bar configuration
bar:
  height: 20
  location: top
  spacing: 5
  margin: 9

  # Default font
  font: mononoki:size=13

  foreground: ffffffff
  background: 000000cc

  left:
    - i3:
       sort: ascending
       anchors: # Not used (directly) by f00bar; used here to avoid duplication
          - string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text: "{name}"}
          - focused: &focused
              deco: {stack: [background: {color: 000000ff}, <<: *std_overline]}
          - invisible: &invisible {foreground: ffffff55}
          - urgent: &urgent
              foreground: 000000ff
              deco: {stack: [background: {color: ffffffff}, <<: *std_overline]}
          - map: &i3_mode
              default:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: {background: {color: cc421dff}}
                - empty: {right-margin: 7}
              conditions:
                mode == default: {empty: {}}
       content:
          "":
            map:
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: [*default, *invisible]}}
                state == urgent:    {string: {<<: [*default, *urgent]}}
       
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{title}"}

  center:
    - clock:
        time-format: "%d %b %H:%M"
        content:
          - string: {text: "{time}"}


  right:
    - network:
        name: enp3s0
        content:
          map:
            conditions:
              ~carrier: {empty: {}}
              carrier:
                map:
                  default: {string: {text: , font: *awesome, foreground: ffffff66}}
                  conditions:
                    state == up && ipv4 != "": {string: {text: , font: *awesome}}
    - alsa:
        card: hw:Generic_1
        mixer: Master
        content:
          map:
            conditions:
              ~online: {string: {text: , font: *awesome, foreground: ff0000ff}}
              online:
                map:
                  on-click: /bin/sh -c "amixer -q sset Master toggle"
                  conditions:
                    muted: {string: {text: , font: *awesome, foreground: ffffff66}}
                    ~muted:
                      ramp:
                        tag: percent
                        items:
                          - string: {text: , font: *awesome}
                          - string: {text: , font: *awesome}
                          - string: {text: , font: *awesome}
    - label:
        content:
          string:
            on-click: session-wl
            text: 
            font: *awesome
